# Generated by Django 3.0 on 2021-06-18 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('1', 'CEO'), ('2', 'Director'), ('3', 'Regional Manager'), ('4', 'Entry Level')], default='4', max_length=100)),
            ],
        ),
    ]
