# Generated by Django 3.2.4 on 2021-06-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='position',
        ),
        migrations.AddField(
            model_name='employees',
            name='options',
            field=models.CharField(choices=[('1', 'CEO'), ('2', 'Director'), ('3', 'Regional Manager'), ('4', 'Entry Level')], default='4', max_length=20),
        ),
        migrations.AlterField(
            model_name='employees',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
