# Generated by Django 3.2.4 on 2021-06-18 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_employees_work_under'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='work_under',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.employees'),
        ),
    ]
